DROP DATABASE demo_app;
CREATE DATABASE demo_app;
USE demo_app;
CREATE TABLE USER (
  ID INT(10) NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(200),
  PASSWORD    VARCHAR (500),
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = latin1;

INSERT INTO USER(ID, NAME, PASSWORD) VALUE (1,'user','1234');